config_name: 'base_config_slices'
data_folder: '/home/quahb/caipi_denoising/data/datasets/base_config_slices'
results_folder: '/home/quahb/caipi_denoising/data/results/base_config_slices'

generate_dataset:
    median_slices: True
    extract_patches: True
    save_dtype: 'float16'

    X_steps:
        - normalize
        - pad_square
        - white_noise
    y_steps:
        - normalize
        - pad_square
    extract_patches_params:
        patch_size: [32, 32]
        extract_step: [32, 32]
        pad_value: -0.5
        pad_before_ext: True
    preprocessing_params:
        normalize:
        pad_square:
            pad_value: -0.5
        white_noise:
            mu: 0.0
            sigma: 0.15

train_network:
    model_type: 0
    input_shape: [null, 32, 32, 1]
    load_model_path: '/home/quahb/caipi_denoising/models/2022-06-01/denoiser_ep02.h5'
    save_model_folder: '/home/quahb/caipi_denoising/models'
    save_model_filename: 'base_config_patches_ep{epoch:02d}.h5'
    valid_split: 0.8
    n_epochs: 10
    init_epoch: 0
    patience: 4
    batch_size: 32
    
predict_test:
    model_type: 0
    load_model_path: '/home/quahb/caipi_denoising/models/2022-06-22/denoiser_ep06.h5'
    extract_patches: False
    input_shape: [null, 384, 384, 1]
    predict_n_slices: 1000
    shuffle: True
    save_dtype: 'float16'
    X_steps:
        - pad_square
    preprocessing_params:
        pad_square:
            pad_value: -0.5
        
gpus_to_use:
- /GPU:0
- /GPU:1
- /GPU:2
- /GPU:3
