config_name: 'base_config'
data_folder: '/home/quahb/caipi_denoising/data/datasets/base_config'
results_folder: '/home/quahb/caipi_denoising/data/results/base_config'
save_model_folder: '/home/quahb/caipi_denoising/models'

train_network:
    model_type: 4
    input_shape: [null, 256, 256, 1]
    load_model_path: null 
    valid_split: 0.8
    n_epochs: 40
    learning_rate: 0.001
    init_epoch: 0
    patience: 4
    batch_size: 32

predict_test:
    train_or_test_set: 'train'
    train_leave_one_out: True
    model_type: 4
    load_model_path: ''
    extract_patches: True
    input_shape: [null, 256, 256, 1]
    extract_step: [64, 64]
    recon_patches: True
    shuffle: False
    seed: 24
    predict_n_slices: null
    save_mode: 'subject'
    save_dtype: 'float16'
    X_steps:
        - standardize
        - pad_square
    gt_steps:
        - standardize
        - pad_sqaure
    preprocessing_params:
        pad_square:
            pad_value: 0.0
        random_xy_flip:
            seed: 24
        white_noise:
            mu: 0.0
            sigma: 0.10
        threshold_intensities:
            value: 5000
        standardize:
            mode: 'subject'
        normalize:
            mode: 'batch'

        
workers: 5
gpus:
- /GPU:0
- /GPU:1
- /GPU:2
- /GPU:3
