config_name: 'base_config'
data_folder: '/home/quahb/caipi_denoising/data/datasets/train/compleximage_full'
results_folder: '/home/quahb/caipi_denoising/data/datasets/test/compleximage_full_cdncnn'
save_dtype: 'complex64'

model_type: 'complex_dncnn'
input_shape: [null, 384, 384, 1]
n_folds: False
test_fold: False
complex_split: False
loss_function: 'mae'

train_network:
    load_model_path: null 
    valid_split: 0.8
    n_epochs: 40
    learning_rate: 0.001
    init_epoch: 0
    patience: 5
    batch_size: 32

predict_test:
    load_model_path: ''
    extract_patches: False
    extract_step: [64, 64]

logging_level: 'info'
workers: 5
gpus:
- /GPU:0
- /GPU:1
- /GPU:2
- /GPU:3
