config_name: 'base_config'
data_folder: '/home/quahb/caipi_denoising/data/datasets/base_config'
results_folder: '/home/quahb/caipi_denoising/data/results/base_config'
save_model_folder: '/home/quahb/caipi_denoising/models'

train_network:
    model_type: 2
    input_shape: [null, 256, 256, 1]
    load_model_path: null 
    valid_split: 0.8
    n_epochs: 40
    learning_rate: 0.001
    init_epoch: 0
    patience: 4
    batch_size: 32

predict_test:
    train_or_test_set: 'test'
    model_type: 2
    load_model_path: ''
    extract_patches: True
    input_shape: [null, 256, 256, 1]
    predict_n_slices: 1024
    recon_patches: True
    shuffle: True
    save_dtype: 'float16'
    X_steps:
        - pad_square
    preprocessing_params:
        pad_square:
            pad_value: 0.0
        
workers: 32
gpus:
- /GPU:0
- /GPU:1
- /GPU:2
- /GPU:3
